In [ ]:
import pandas as pd

# 定义一个转换函数：将数值转换为6位字符串，前面补0
def to_six_digit_str(x):
    try:
        return f"{int(x):06d}"
    except:
        return x  # 如果转换失败，保留原值（可选）

# 读取CSV，并对 'Stkcd' 列应用转换函数
df_inner = pd.read_csv(
    'inner.csv',
    dtype={'company_id': str},  # 先以字符串读入（防止前置0被丢弃）
    converters={'company_id': to_six_digit_str}  # 再用函数处理
)

df_st = pd.read_csv(
    'fdp.csv',
    dtype={'company_id': str},  # 先以字符串读入（防止前置0被丢弃）
    converters={'company_id': to_six_digit_str}  # 再用函数处理
)

In [2]:
df_st

,Stkcd,target,year_1,year_2,embedding_0,embedding_1,embedding_2,embedding_3,embedding_4,embedding_5,...,embedding_119,embedding_120,embedding_121,embedding_122,embedding_123,embedding_124,embedding_125,embedding_126,embedding_127,dataset
0,2,0.0,2010,2011,0.964028,-2.895508e-23,0.0,0.0,-1.840623e-12,0.0,...,1.154781e-30,8.260624e-17,-0.0,0.0,-2.494888e-35,0.761594,-0.761594,-0.761594,0.0,train
1,2,0.0,2011,2012,0.964028,-2.709050e-23,0.0,0.0,-2.436380e-12,0.0,...,7.923801e-31,4.954916e-17,-0.0,0.0,-2.935651e-35,0.761594,-0.761594,-0.761594,0.0,train
2,2,0.0,2012,2013,0.964028,-2.080931e-23,0.0,0.0,-2.678098e-12,0.0,...,6.245424e-31,5.684070e-17,-0.0,0.0,-4.089037e-35,0.761594,-0.761594,-0.761594,0.0,train
3,2,0.0,2013,2014,0.964028,-1.907495e-23,0.0,0.0,-3.222539e-12,0.0,...,6.402951e-31,6.326300e-17,-0.0,0.0,-6.991075e-35,0.761594,-0.761594,-0.761594,0.0,train
4,2,0.0,2014,2015,0.964028,-1.845482e-23,0.0,0.0,-2.808927e-12,0.0,...,4.555814e-31,4.314276e-17,-0.0,0.0,-5.214611e-35,0.761594,-0.761594,-0.761594,0.0,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5395,601890,0.0,2020,2021,0.964028,-2.610599e-24,0.0,0.0,-2.719723e-12,0.0,...,4.408073e-31,1.929309e-17,-0.0,0.0,-2.280966e-34,0.761594,-0.761594,-0.761594,0.0,test
5396,601890,0.0,2021,2022,0.964028,-1.877628e-24,0.0,0.0,-6.372212e-12,0.0,...,2.570029e-31,2.574708e-17,-0.0,0.0,-2.545209e-34,0.761594,-0.761594,-0.761594,0.0,test
5397,601919,0.0,2019,2020,0.964028,-5.782044e-24,0.0,0.0,-7.604363e-12,0.0,...,1.254856e-31,1.940891e-17,-0.0,0.0,-1.608570e-34,0.761594,-0.761594,-0.761594,0.0,test
5398,601919,0.0,2020,2021,0.964028,-6.326324e-24,0.0,0.0,-4.449065e-12,0.0,...,1.538890e-31,1.497004e-17,-0.0,0.0,-1.382428e-34,0.761594,-0.761594,-0.761594,0.0,test
5399,601919,0.0,2021,2022,0.964028,-5.192767e-24,0.0,0.0,-7.785497e-12,0.0,...,1.057397e-31,1.753977e-17,-0.0,0.0,-1.669157e-34,0.761594,-0.761594,-0.761594,0.0,test

In [3]:
df_inner

,Stkcd,target,year_1,year_2,embedding_0,embedding_1,embedding_2,embedding_3,embedding_4,embedding_5,...,embedding_119,embedding_120,embedding_121,embedding_122,embedding_123,embedding_124,embedding_125,embedding_126,embedding_127,dataset
0,2,0.0,2010,2011,0.964028,0.0,0.964028,0.0,0.0,0.0,...,0.0,-0.964028,0.0,0.0,0.761594,0.0,-0.964028,0.0,0.0,train
1,2,0.0,2011,2012,0.964028,0.0,0.964028,0.0,0.0,0.0,...,0.0,-0.964028,0.0,0.0,0.761594,0.0,-0.964028,0.0,0.0,train
2,2,0.0,2012,2013,0.964028,0.0,0.964028,0.0,0.0,0.0,...,0.0,-0.964028,0.0,0.0,0.761594,0.0,-0.964028,0.0,0.0,train
3,2,0.0,2013,2014,0.964028,0.0,0.964028,0.0,0.0,0.0,...,0.0,-0.964028,0.0,0.0,0.761594,0.0,-0.964028,0.0,0.0,train
4,2,0.0,2014,2015,0.964028,0.0,0.964028,0.0,0.0,0.0,...,0.0,-0.964028,0.0,0.0,0.761594,0.0,-0.964028,0.0,0.0,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5395,601890,1.0,2020,2021,0.964028,0.0,0.964028,0.0,0.0,0.0,...,0.0,-0.964028,0.0,0.0,0.761594,0.0,-0.964028,0.0,0.0,test
5396,601890,0.0,2021,2022,0.964028,0.0,0.964028,0.0,0.0,0.0,...,0.0,-0.964028,0.0,0.0,0.761594,0.0,-0.964028,0.0,0.0,test
5397,601919,1.0,2019,2020,0.964028,0.0,0.964028,0.0,0.0,0.0,...,0.0,-0.964028,0.0,0.0,0.761594,0.0,-0.964028,0.0,0.0,test
5398,601919,1.0,2020,2021,0.964028,0.0,0.964028,0.0,0.0,0.0,...,0.0,-0.964028,0.0,0.0,0.761594,0.0,-0.964028,0.0,0.0,test
5399,601919,1.0,2021,2022,0.964028,0.0,0.964028,0.0,0.0,0.0,...,0.0,-0.964028,0.0,0.0,0.761594,0.0,-0.964028,0.0,0.0,test

In [ ]:
df_inner.drop("dataset", axis=1, inplace=True)

In [ ]:
df = pd.merge(df_inner, df_st, on=['Stkcd', 'year_1', 'year_2'], how='inner')
df

In [7]:
df.to_csv("concated_2_vectors.csv", index=False)